version: '3.3'

services:

  app:
    build:
      context: .
      args:
        - mode=DEV
    container_name: app-container
    volumes:
      - ./project:/app/project
      - ./scripts:/app/scripts
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  

  db:
    image: postgres:15
    container_name: postgres-container
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=dev-pass
      - POSTGRES_DB=dev-db

volumes:
  postgres-data: